### ISSUE TITLE
Add readme, requirements.txt

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/Binod-Merchandise#1]
### 🚀Feature Request
Add a readme for setup and requirements.txt for the backend

### Description
The project is not documented properly with a readme and requirements for setup

### Describe the solution you'd like
Create a readme file with all necessary headings and content. Refer to other open source project's readme
Freeze a requirements.txt for setting up the python backend in FastAPI

### Additional context
Readme should contain the project setup, how to run, structure details and basic descriptions. Any other additions you want to do are welcome

**Comment by mangalgithub** [comment]
Can you assign this issue to me.

**Comment by shivansh196** [comment]
Can the issue be assigned to me

**Comment by sharmavasant** [comment]
can u assign me

**Comment by PriyavKaneria** [comment]
According to rules @akshatvermavi has been assigned the issue on contrihub
