### ISSUE TITLE
Migrate to SQlite db from json file based db

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/Binod-Merchandise#2]
### 🚀Feature Request
Migrate to SQlite db from json file based db

### Description
Currently the backend uses a database.json file as database.
This is not scalable

### Describe the solution you'd like
Migrate to a SQLite database using any third-party ORM or engine for python sqlite integration

### Additional context
Please decide and mention any third party library in comments before using it for mentor advice

**Comment by lokesh-wagh** [comment]
hey @PriyavKaneria  

I would like to work on this issue 
request for the same through contrihub

i plan to use sqlAlchemy for this

**Comment by PriyavKaneria** [comment]
I'll assign once you complete your current active issue

**Comment by lokesh-wagh** [comment]
Hey @PriyavKaneria I have already made a PR for my current issue


can you assign me this issue??

**Comment by lokesh-wagh** [comment]
Sir I have completed this issue

waiting for assignment from you then I can open a PR

**Comment by lokesh-wagh** [comment]
Hey @PriyavKaneria I have made a PR can you review it??
