### ISSUE TITLE
Backend: More secure email, password configuration

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/Binod-Merchandise#3]
### 🚀Feature Request
Backend: More secure email, password configuration

### Description
Currently email and password are stored in __init__ file which is **_really_** insecure
Change the configuration such that it is more secure

### Describe the solution you'd like
Hint: Research environment variables and how to use them in python (FastAPI)

**Comment by mangalgithub** [comment]
Can you assign this issue to me.

**Comment by lokesh-wagh** [comment]
I think if we use dotenv package's  to load the enviornment variable's then use them in file 

this would be more secure

**Comment by lokesh-wagh** [comment]
I would like to work in this issue 

Can you assign it to me

**Comment by shivansh196** [comment]
Please assign me this issue, I have solved it. Here we will use the the .env file with importing the fastapi and decouple. And then the .env file must kept in the gitignore file as well.

**Comment by PriyavKaneria** [comment]
According to rules @shivansh196  has been assigned the issue on contrihub.
Also please wait for issue assignment before submitting a pull request

**Comment by shivansh196** [comment]
I have submitted the request, do I have to make any further changes to it @PriyavKaneria

**Comment by PriyavKaneria** [comment]
Mention the issue as fixes in the PR description
Also make suggested changes on PR
@shivansh196

**Comment by PriyavKaneria** [comment]
@madhvendraprasad you can work on this. You can refer the closed PR on this to refer past mistakes

**Comment by priyanshagra** [comment]
sir please assign this i requested on contrihub

**Comment by priyanshagra** [comment]
if assigned to someone else please rejeect my request
![Screenshot 2023-10-15 143043](https://github.com/ContriHUB/Binod-Merchandise/assets/127022024/056cdffd-5b09-43b2-9224-a49ec2491ac0)

**Comment by PriyavKaneria** [comment]
@madhvendraprasad are you working on this? If not please inform

**Comment by Madhvendraprasad** [comment]
No sir, I am not working on this issue.

**Comment by PriyavKaneria** [comment]
@Madhvendraprasad then you should not have raised a Issue Assignment Request. Isse assigned to @priyanshagra

**Comment by Madhvendraprasad** [comment]
Sorry sir.
I wanted to work on that issue but I wasn't able to do so due to some other
urgent works.
