### ISSUE TITLE
Frontend & backend: Add upload image functionality to add product

### ISSUE THREAD

**Issue by PriyavKaneria** [ContriHUB/Binod-Merchandise#4]
### 🚀Feature Request
Frontend: Add upload image functionality to add product

### Description
Currently, the images are randomly assigned to each product on addition. Design and make changes to the UI as well as make APIs to allow user to upload image while adding product.

### Describe the solution you'd like
Image can be uploaded as a file saved in a data folder in the running server. (Or if you know how to, then use cloud storage)

### Additional context
Store the path (relative) in the database for each item

**Comment by reharsh** [comment]
can i be assigned to this issue, already requested on contrihub.

**Comment by reharsh** [comment]
@PriyavKaneria sir, submitted a PR please look into it.
